/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:8063044f-363b-4c1f-b6fe-9b5b251959a7",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_yNAGsWZ2D",
    "aws_user_pools_web_client_id": "5o2u8kiookc8kn84506iqcc04m",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "eu-west-1",
            "maps": {
                "items": {
                    "mapcbd6d1fe-dev": {
                        "style": "RasterEsriImagery"
                    }
                },
                "default": "mapcbd6d1fe-dev"
            }
        }
    }
};


export default awsmobile;
